FileError - ошибка, возникшая во время чтения файла
===================================================


.. py:class:: FileError()


    .. py:attribute:: code

        Это свой­ст­во оп­ре­де­ля­ет тип воз­ник­шей ошиб­ки. 
        
        * `NOT_FOUND_ERR` = 1, Файл не су­ще­ст­ву­ет. (Воз­мож­но, был уда­лен по­сле то­го, как поль­зо­ва­тель вы­брал его, но пе­ред тем, как про­грам­ма по­пы­та­лась про­чи­тать его.)
        
        * `SECURITY_ERR` = 2, Не­оп­ре­де­лен­ная про­бле­ма, свя­зан­ная с без­опас­но­стью, вы­ну­ж­даю­щая бро­узер за­ пре­тить ва­шей про­грам­ме чи­тать файл.
        
        * `ABORT_ERR` = 3, Опе­ра­ция чте­ния фай­ла бы­ла пре­рва­на.
        
        * `NOT_READABLE_ERR` = 4, Файл не­дос­ту­пен для чте­ния, воз­мож­но, по­то­му что из­ме­ни­лись пра­ва дос­ту­па к не­му или дру­гой про­цесс за­бло­ки­ро­вал файл.
        
        * `ENCODING_ERR` = 5, Вы­зов readAsDataURL() по­тер­пел не­уда­чу, по­то­му что файл ока­зал­ся слиш­ком длин­ным, что­бы пред­ста­вить его в ви­де URL-ад­ре­са data://.